Server/src/main/java/org/xdi/oxauth/audit/debug/entity/HttpRequest.java
package org.xdi.oxauth.audit.debug.entity;

import java.util.Map;

/**
 * Created by eugeniuparvan on 5/15/17.
 */
public class HttpRequest {
    private String senderIP;
    private String method;
    private String path;
    private Map<String, String> params;
    private Map<String, String> headers;
    private String body;

    public String getSenderIP() {
        return senderIP;
    }

    public void setSenderIP(String senderIP) {
        this.senderIP = senderIP;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Map<String, String> getParams() {
        return params;
    }

    public void setParams(Map<String, String> params) {
        this.params = params;
    }

    public Map<String, String> getHeaders() {
        return headers;
    }

    public void setHeaders(Map<String, String> headers) {
        this.headers = headers;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }
}

Server/src/main/java/org/xdi/oxauth/audit/debug/entity/HttpResponse.java
package org.xdi.oxauth.audit.debug.entity;

import java.util.Map;

/**
 * Created by eugeniuparvan on 5/15/17.
 */
public class HttpResponse {
    private int status;
    private Map<String, String> headers;

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Map<String, String> getHeaders() {
        return headers;
    }

    public void setHeaders(Map<String, String> headers) {
        this.headers = headers;
    }
}

Server/src/main/java/org/xdi/oxauth/cert/validation/model/ValidationStatus.java
/*
 * oxAuth is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.xdi.oxauth.cert.validation.model;

import java.security.cert.X509Certificate;
import java.util.Date;

/**
 * Certificate validation status
 * 
 * @author Yuriy Movchan
 * @version March 10, 2016
 */
public class ValidationStatus {

	private X509Certificate certificate;
	private X509Certificate issuer;

	private CertificateValidity validity;
	private ValidatorSourceType sourceType;

	private Date revocationObjectIssuingTime;
	private Date revocationDate;
	private Date validationDate;

	public ValidationStatus(X509Certificate certificate, X509Certificate issuer, Date validationDate, ValidatorSourceType sourceType,
			CertificateValidity validity) {
		this.certificate = certificate;
		this.issuer = issuer;
		this.validationDate = validationDate;
		this.sourceType = sourceType;
		this.validity = validity;
	}

	public X509Certificate getCertificate() {
		return certificate;
	}

	public void setCertificate(X509Certificate certificate) {
		this.certificate = certificate;
	}

	public X509Certificate getIssuer() {
		return issuer;
	}

	public void setIssuer(X509Certificate issuer) {
		this.issuer = issuer;
	}

	public CertificateValidity getValidity() {
		return validity;
	}

	public void setValidity(CertificateValidity validity) {
		this.validity = validity;
	}

	public ValidatorSourceType getSourceType() {
		return sourceType;
	}

	public void setSourceType(ValidatorSourceType sourceType) {
		this.sourceType = sourceType;
	}

	public Date getRevocationObjectIssuingTime() {
		return revocationObjectIssuingTime;
	}

	public void setRevocationObjectIssuingTime(Date revocationObjectIssuingTime) {
		this.revocationObjectIssuingTime = revocationObjectIssuingTime;
	}

	public Date getRevocationDate() {
		return revocationDate;
	}

	public void setRevocationDate(Date revocationDate) {
		this.revocationDate = revocationDate;
	}

	public Date getValidationDate() {
		return validationDate;
	}

	public void setValidationDate(Date validationDate) {
		this.validationDate = validationDate;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CertificateValidationStatus [certificate=").append(certificate.getSerialNumber()).append(", issuer=").append(issuer.getSerialNumber()).append(", validity=")
				.append(validity).append(", sourceType=").append(sourceType).append(", revocationObjectIssuingTime=")
				.append(revocationObjectIssuingTime).append(", revocationDate=").append(revocationDate).append(", validationDate=").append(validationDate)
				.append("]");
		return builder.toString();
	}

	public enum ValidatorSourceType {
		OCSP, CRL, APP, CHAIN, SELF_SIGNED
	}

	public enum CertificateValidity {
		VALID, INVALID, REVOKED, UNKNOWN
	}

}

Server/src/main/java/org/xdi/oxauth/model/appliance/Entry.java
/*
 * oxAuth is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.xdi.oxauth.model.appliance;

import org.gluu.site.ldap.persistence.annotation.LdapDN;

/**
 * Provides DN attribute
 *
 * @author Yuriy Movchan Date: 10.07.2010
 */
public class Entry {

	@LdapDN
	private String dn;

	public Entry() {}

	public Entry(String dn) {
		super();
		this.dn = dn;
	}

	public String getDn() {
		return dn;
	}

	public void setDn(String dn) {
		this.dn = dn;
	}

	public String getBaseDn() {
		return dn;
	}

	public void setBaseDn(String dn) {
		this.dn = dn;
	}

	@Override
	public String toString() {
		return String.format("Entry [dn=%s]", dn);
	}

}

Server/src/main/java/org/xdi/oxauth/model/appliance/InumEntry.java
/*
 * oxAuth is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.xdi.oxauth.model.appliance;

import org.gluu.site.ldap.persistence.annotation.LdapAttribute;
import org.gluu.site.ldap.persistence.annotation.LdapEntry;
import org.gluu.site.ldap.persistence.annotation.LdapObjectClass;

/**
 * Provides global inum search ability.
 * @author Oleksiy Tataryn
 *
 */
@LdapEntry
@LdapObjectClass(values = { "top" })
public class InumEntry extends Entry {

	@LdapAttribute(ignoreDuringUpdate = true)
	private String inum;

	/**
	 * @param inum the inum to set
	 */
	public void setInum(String inum) {
		this.inum = inum;
	}


	/**
	 * @return the inum
	 */
	public String getInum() {
		return inum;
	}


	@Override
	public String toString() {
		return String.format("Entry [dn=%s, inum=%s]", getDn(), getInum());
	}


}

Server/src/main/java/org/xdi/oxauth/model/audit/Action.java
package org.xdi.oxauth.model.audit;

public enum Action {
    CLIENT_REGISTRATION("CLIENT_REGISTRATION"),
    CLIENT_UPDATE("CLIENT_UPDATE"),
    CLIENT_READ("CLIENT_READ"),
    CLIENT_DELETE("CLIENT_DELETE"),
    USER_AUTHORIZATION("USER_AUTHORIZATION"),
    USER_INFO("USER_INFO"),
    TOKEN_REQUEST("TOKEN_REQUEST"),
    TOKEN_VALIDATE("TOKEN_VALIDATE"),
    SESSION_UNAUTHENTICATED("SESSION_UNAUTHENTICATED"),
    SESSION_AUTHENTICATED("SESSION_AUTHENTICATED"),
    SESSION_DESTROYED("SESSION_DESTROYED");

    private String value;

    Action(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value;
    }
}

Server/src/main/java/org/xdi/oxauth/model/authorize/ClaimValueType.java
/*
 * oxAuth is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.xdi.oxauth.model.authorize;

/**
 * @author Javier Rojas Blum Date: 03.21.2012
 */
public enum ClaimValueType {
    NULL,
    ESSENTIAL_TRUE,
    ESSENTIAL_FALSE,
    VALUE_LIST,
    SINGLE_VALUE;
}

Server/src/main/java/org/xdi/oxauth/model/common/AbstractAuthorizationGrant.java
/*
 * oxAuth is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.xdi.oxauth.model.common;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.CopyOnWriteArraySet;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xdi.oxauth.model.authorize.JwtAuthorizationRequest;
import org.xdi.oxauth.model.authorize.ScopeChecker;
import org.xdi.oxauth.model.configuration.AppConfiguration;
import org.xdi.oxauth.model.ldap.TokenLdap;
import org.xdi.oxauth.model.registration.Client;
import org.xdi.oxauth.util.TokenHashUtil;

/**
 * @author Yuriy Zabrovarnyy
 * @author Javier Rojas Blum
 * @author Yuriy Movchan
 * @version September 6, 2017
 */

public abstract class AbstractAuthorizationGrant implements IAuthorizationGrant {

    private static final Logger log = LoggerFactory.getLogger(AbstractAuthorizationGrant.class);

    @Inject
    protected AppConfiguration appConfiguration;

    @Inject
    protected ScopeChecker scopeChecker;

    private User user;
    private AuthorizationGrantType authorizationGrantType;
    private Client client;
    private Set<String> scopes;

    private String grantId;
    private JwtAuthorizationRequest jwtAuthorizationRequest;
    private Date authenticationTime;
    private TokenLdap tokenLdap;
    private AccessToken longLivedAccessToken;
    private IdToken idToken;
    private AuthorizationCode authorizationCode;
    private String tokenBindingHash;
    private String nonce;
    private String codeChallenge;
    private String codeChallengeMethod;
    private String claims;

    private String acrValues;
    private String sessionDn;

    protected final ConcurrentMap<String, AccessToken> accessTokens = new ConcurrentHashMap<String, AccessToken>();
    protected final ConcurrentMap<String, RefreshToken> refreshTokens = new ConcurrentHashMap<String, RefreshToken>();

    public AbstractAuthorizationGrant() {
    }

    protected AbstractAuthorizationGrant(User user, AuthorizationGrantType authorizationGrantType, Client client,
                                         Date authenticationTime) {
        init(user, authorizationGrantType, client, authenticationTime);
    }

    protected void init(User user, AuthorizationGrantType authorizationGrantType, Client client,
                        Date authenticationTime) {
        this.authenticationTime = authenticationTime != null ? new Date(authenticationTime.getTime()) : null;
        this.user = user;
        this.authorizationGrantType = authorizationGrantType;
        this.client = client;
        this.scopes = new CopyOnWriteArraySet<String>();
        this.grantId = UUID.randomUUID().toString();
    }

    @Override
    public synchronized String getGrantId() {
        return grantId;
    }

    @Override
    public synchronized void setGrantId(String p_grantId) {
        grantId = p_grantId;
    }

    /**
     * Returns the {@link AuthorizationCode}.
     *
     * @return The authorization code.
     */
    @Override
    public AuthorizationCode getAuthorizationCode() {
        return authorizationCode;
    }

    /**
     * Sets the {@link AuthorizationCode}.
     *
     * @param authorizationCode The authorization code.
     */
    @Override
    public void setAuthorizationCode(AuthorizationCode authorizationCode) {
        this.authorizationCode = authorizationCode;
    }

    public String getTokenBindingHash() {
        return tokenBindingHash;
    }

    public void setTokenBindingHash(String tokenBindingHash) {
        this.tokenBindingHash = tokenBindingHash;
    }

    @Override
    public String getNonce() {
        return nonce;
    }

    @Override
    public void setNonce(String nonce) {
        this.nonce = nonce;
    }

    public String getCodeChallenge() {
        return codeChallenge;
    }

    public void setCodeChallenge(String codeChallenge) {
        this.codeChallenge = codeChallenge;
    }

    public String getCodeChallengeMethod() {
        return codeChallengeMethod;
    }

    public void setCodeChallengeMethod(String codeChallengeMethod) {
        this.codeChallengeMethod = codeChallengeMethod;
    }

    public String getClaims() {
        return claims;
    }

    public void setClaims(String claims) {
        this.claims = claims;
    }

    /**
     * Returns a list with all the issued refresh tokens codes.
     *
     * @return List with all the issued refresh tokens codes.
     */
    @Override
    public Set<String> getRefreshTokensCodes() {
        return refreshTokens.keySet();
    }

    /**
     * Returns a list with all the issued access tokens codes.
     *
     * @return List with all the issued access tokens codes.
     */
    @Override
    public Set<String> getAccessTokensCodes() {
        return accessTokens.keySet();
    }

    /**
     * Returns a list with all the issued access tokens.
     *
     * @return List with all the issued access tokens.
     */
    @Override
    public List<AccessToken> getAccessTokens() {
        return new ArrayList<AccessToken>(accessTokens.values());
    }

    @Override
    public void setScopes(Collection<String> scopes) {
        this.scopes.clear();
        this.scopes.addAll(scopes);
    }

    @Override
    public AccessToken getLongLivedAccessToken() {
        return longLivedAccessToken;
    }

    @Override
    public void setLongLivedAccessToken(AccessToken longLivedAccessToken) {
        this.longLivedAccessToken = longLivedAccessToken;
    }

    @Override
    public IdToken getIdToken() {
        return idToken;
    }

    @Override
    public void setIdToken(IdToken idToken) {
        this.idToken = idToken;
    }

    @Override
    public TokenLdap getTokenLdap() {
        return tokenLdap;
    }

    @Override
    public void setTokenLdap(TokenLdap p_tokenLdap) {
        this.tokenLdap = p_tokenLdap;
    }

    /**
     * Returns the resource owner's.
     *
     * @return The resource owner's.
     */
    @Override
    public User getUser() {
        return user;
    }

    public String getAcrValues() {
        return acrValues;
    }

    public void setAcrValues(String acrValues) {
        this.acrValues = acrValues;
    }

    public String getSessionDn() {
        return sessionDn;
    }

    public void setSessionDn(String sessionDn) {
        this.sessionDn = sessionDn;
    }

    /**
     * Checks the scopes policy configured according to the type of the
     * authorization grant to limit the issued token scopes.
     *
     * @param requestedScopes A space-delimited list of values in which the order of values
     *                        does not matter.
     * @return A space-delimited list of scopes
     */
    @Override
    public String checkScopesPolicy(String requestedScopes) {
        this.scopes.clear();

        Set<String> grantedScopes = scopeChecker.checkScopesPolicy(client, requestedScopes);
        this.scopes.addAll(grantedScopes);

        final StringBuilder grantedScopesSb = new StringBuilder();
        for (String scope : scopes) {
            grantedScopesSb.append(" ").append(scope);
        }

        final String grantedScopesSt = grantedScopesSb.toString().trim();

        return grantedScopesSt;
    }

    @Override
    public AccessToken createAccessToken() {
        int lifetime = appConfiguration.getAccessTokenLifetime();
        AccessToken accessToken = new AccessToken(lifetime);

        accessToken.setAuthMode(getAcrValues());
        accessToken.setSessionDn(getSessionDn());

        return accessToken;
    }

    @Override
    public RefreshToken createRefreshToken() {
        int lifetime = appConfiguration.getRefreshTokenLifetime();
        if (client.getRefreshTokenLifetime() != null && client.getRefreshTokenLifetime() > 0) {
            lifetime = client.getRefreshTokenLifetime();
        }

        RefreshToken refreshToken = new RefreshToken(lifetime);

        refreshToken.setAuthMode(getAcrValues());
        refreshToken.setSessionDn(getSessionDn());

        return refreshToken;
    }

    @Override
    public String getUserId() {
        if (user == null) {
            return null;
        }

        return user.getUserId();
    }

    @Override
    public String getUserDn() {
        if (user == null) {
            return null;
        }

        return user.getDn();
    }

    /**
     * Returns the {@link AuthorizationGrantType}.
     *
     * @return The authorization grant type.
     */
    @Override
    public AuthorizationGrantType getAuthorizationGrantType() {
        return authorizationGrantType;
    }

    /**
     * Returns the {@link org.xdi.oxauth.model.registration.Client}. An
     * application making protected resource requests on behalf of the resource
     * owner and with its authorization.
     *
     * @return The client.
     */
    @Override
    public Client getClient() {
        return client;
    }

    @Override
    public String getClientId() {
        if (client == null) {
            return null;
        }

        return client.getClientId();
    }

    @Override
    public String getClientDn() {
        if (client == null) {
            return null;
        }

        return client.getDn();
    }

    @Override
    public Date getAuthenticationTime() {
        return authenticationTime;
    }

    public void setAuthenticationTime(Date authenticationTime) {
        this.authenticationTime = authenticationTime;
    }

    /**
     * Returns a list of the scopes granted to the client.
     *
     * @return List of the scopes granted to the client.
     */
    @Override
    public Set<String> getScopes() {
        return scopes;
    }

    @Override

Server/src/main/webapp/authorize.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
				xmlns:f="http://xmlns.jcp.org/jsf/core"
				xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
				xmlns:h="http://xmlns.jcp.org/jsf/html"
				template="/WEB-INF/incl/layout/authorize-extended-template.xhtml">

	<f:metadata>
		<f:viewAction action="#{authorizeAction.checkUiLocales}" />
		<f:viewAction action="#{authorizeAction.checkPermissionGranted}" />

		<!-- OAuth 2.0 request parameters -->
		<f:viewParam name="scope" value="#{authorizeAction.scope}" />
		<f:viewParam name="response_type" value="#{authorizeAction.responseType}" />
		<f:viewParam name="client_id" value="#{authorizeAction.clientId}" />
		<f:viewParam name="redirect_uri" value="#{authorizeAction.redirectUri}" />
		<f:viewParam name="state" value="#{authorizeAction.state}" />

		<!-- OpenID Connect request parameters -->
		<f:viewParam name="response_mode" value="#{authorizeAction.responseMode}" />
		<f:viewParam name="nonce" value="#{authorizeAction.nonce}" />
		<f:viewParam name="display" value="#{authorizeAction.display}" />
		<f:viewParam name="prompt" value="#{authorizeAction.prompt}" />
		<f:viewParam name="max_age" value="#{authorizeAction.maxAge}" />
		<f:viewParam name="ui_locales" value="#{authorizeAction.uiLocales}" />
		<f:viewParam name="id_token_hint" value="#{authorizeAction.idTokenHint}" />
		<f:viewParam name="login_hint" value="#{authorizeAction.loginHint}" />
		<f:viewParam name="acr_values" value="#{authorizeAction.acrValues}" />
		<f:viewParam name="amr_values" value="#{authorizeAction.amrValues}" />
		<f:viewParam name="request" value="#{authorizeAction.request}" />
		<f:viewParam name="request_uri" value="#{authorizeAction.requestUri}" />
		<f:viewParam name="code_challenge" value="#{authorizeAction.codeChallenge}" />
		<f:viewParam name="code_challenge_method" value="#{authorizeAction.codeChallengeMethod}" />
		<f:viewParam name="claims" value="#{authorizeAction.claims}" />

		<!-- custom oxAuth parameters -->
		<f:viewParam name="session_id" value="#{authorizeAction.sessionId}" />
	</f:metadata>

	<ui:param name="_client" value="#{clientService.getClient(request.getParameter('client_id'))}" />
	<ui:param name="_scopes" value="#{authorizeAction.scopes}" />
	<ui:param name="_requestedClaims" value="#{authorizeAction.requestedClaims}" />

    <ui:define name="controlButttons">
		<h:commandLink id="doNotAllowButton"  class="button button-default"
					   value="#{msgs['authorize.doNotAllow']}"
					   action="#{authorizeAction.permissionDenied}" />&nbsp;
		<h:commandLink id="allowButton" class="button button-primary"
					   value="#{msgs['authorize.allow']}"
					   action="#{authorizeAction.permissionGranted}" />
	</ui:define>

</ui:composition>

Server/src/main/webapp/error.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	template="/WEB-INF/incl/layout/login-template.xhtml">

	<ui:param name="showGlobalMessages" value="false" />

	<ui:define name="body">
		<header class="bs-docs-nav navbar navbar-static-top" id="top">
		<div class="container">
			<div class="logo span2">
				<h:panelGroup layout="block" rendered='#{empty client.logoUri}'>
					<object data="ext/resources/img/logo.png" type="image/png">
						<img src="img/logo.png" />
					</object>
				</h:panelGroup>
			</div>
		</div>
		</header>
		<div class="bs-docs-section"
			style="padding-bottom: 1px; border-top: 2px solid #1ab26b !important;"></div>
		<div class="container-fluid"
			style="padding-bottom: 5%; width: 50%; height: 50%;">
			<div class="row">
				<div class="text-center col-sm-12">
					<div class="section">
						<h1
							style="font-size: 3em; font-weight: bold; font-family: Arial">
							OOPS</h1>
					</div>
					<div class="section text-center">
						<p>
							<h:outputFormat value="#{msgs['error.unexpectedError']}">
								<f:param value="#{pageService.currentDateTime}" />
							</h:outputFormat>
						</p>
						<div class="body text-center">
							<h:messages id="globalMessage" styleClass="message text-center"
								errorClass="errormsg" infoClass="infomsg" warnClass="warnmsg"
								globalOnly="true" />
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-copyright text-center py-3"
			style="background: #1ab26b; position: fixed; left: 0; bottom: 0; width: 100%; text-align: center;">
			<div class="footer">
				<div class="row">
					<div class="col-md-12">
						<div class="padding_spc"
							style="padding-bottom: 5px; padding-top: 5px;">
							<p>
								<h:outputText value="#{msgs['common.gluuInc']}" />
								| <a target="_blank"
									href="https://github.com/GluuFederation/oxAuth/blob/master/LICENSE"><h:outputText
										value="#{msgs['common.caution']}" escape="false" /></a>
								<h:panelGroup rendered='#{!empty client.policyUri}'>
					| <a target="_blank" href="#{client.policyUri}"><h:outputText
											value="#{msgs['common.privacyPolicy']}" escape="false" /></a>
								</h:panelGroup>
								<h:panelGroup rendered='#{!empty client.tosUri}'>
					| <a target="_blank" href="#{client.tosUri}"><h:outputText
											value="#{msgs['common.termsOfService']}" escape="false" /></a>
								</h:panelGroup>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>

	</ui:define>

</ui:composition>

Server/src/main/webapp/error_service.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
				xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
				xmlns:f="http://xmlns.jcp.org/jsf/core"
				xmlns:h="http://xmlns.jcp.org/jsf/html"
				template="/WEB-INF/incl/layout/template.xhtml">

	<ui:param name="showGlobalMessages" value="false"/>

	<ui:define name="body">
		<div class="section">
			<h1>#{msgs['error.errorEncountered']}</h1>
		</div>

		<div class="section">
			<p>
				<h:outputFormat value="#{msgs['error.unexpectedError']}">
					<f:param value="#{pageService.currentDateTime}"/>
				</h:outputFormat>
			</p>

			<div class="body">
				<h:messages id="globalMessage" styleClass="message"
							errorClass="errormsg" infoClass="infomsg" warnClass="warnmsg"
							globalOnly="true" />
			</div>
		</div>
	</ui:define>

</ui:composition>

Server/src/main/webapp/index.jsp
<% response.sendRedirect(".well-known/openid-configuration"); %>

Server/src/main/webapp/logout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

	<f:view xmlns="http://www.w3.org/1999/xhtml" contentType="text/html" locale="#{language.localeCode}">
		<f:metadata>
			<f:viewAction action="#{identity.logout}" />
			<f:viewAction action="#{logoutAction.redirect}" />
	
			<f:viewParam name="id_token_hint" value="#{logoutAction.idTokenHint}" />
			<f:viewParam name="post_logout_redirect_uri" value="#{logoutAction.postLogoutRedirectUri}" />
		</f:metadata>
	</f:view>
</html>

Server/src/main/webapp/opiframe.xhtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>
        oxAuth - OP iFrame
    </title>
    <script type="text/javascript" src="js/crypto-js-3.1.9-1/crypto-js.js"></script>
    <script>
        //<![CDATA[
        window.addEventListener("message", receiveMessage, false);

        function receiveMessage(e) {
            var message = e.data;
            var client_id = message.split(' ')[0];
            var session_state = message.split(' ')[1];

            var salt = session_state.split('.')[1];
            var op_browser_state = getCookie("session_state");

            var ss = CryptoJS.SHA256(client_id + ' ' + e.origin + ' ' + op_browser_state + ' ' + salt) + "." + salt;

            if (session_state == ss) {
                stat = "unchanged";
            } else {
                stat = "changed";
            }

            e.source.postMessage(stat, e.origin);
        }

        function getCookie(cookieName) {
            var x, y, cookies = document.cookie.split(";");
            for (var i = 0; i < cookies.length; i++) {
                x = cookies[i].substr(0, cookies[i].indexOf("="));
                y = cookies[i].substr(cookies[i].indexOf("=") + 1);
                x = x.replace(/^\s+|\s+$/g, "");
                if (x == cookieName) {
                    return decodeURI(y);
                }
            }
        }
        //]]>
    </script>
</head>
<body></body>
</html>

Server/src/main/webapp/postlogin.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<f:view contentType="text/html">
	<f:metadata>
		<f:viewAction action="#{authenticator.authenticateWithOutcome}" />
	</f:metadata>
</f:view>

</html>